### PR TITLE
use validated variable $my_enable_stats in template

### PR DESCRIPTION
**Pull request by Phil-Friderici**
fix found by @vobelic

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Odd messages from travis

**Comment by Phil-Friderici** [comment]
@ghoneycutt please have a look at this minimalistic bugfix. Without this patch $enable_stats will always be 'false'.

**Comment by ghoneycutt** [comment]
Thanks!

Waiting on PR #73 which deals with validating enable_stats and adds spec tests as well as some other testing related PR's before merging.

**Comment by ghoneycutt** [comment]
Released in v3.5.3

**Pull request merged**
