### PR TITLE
Fix default service name for Suse SLE12

### PR DESCRIPTION
**Pull request by jwennerberg**
$ cat /etc/os-release 
    NAME="SLES"
    VERSION="12"
    VERSION_ID="12"
    PRETTY_NAME="SUSE Linux Enterprise Server 12"
    ID="sles"
    ANSI_COLOR="0;32"
    CPE_NAME="cpe:/o:suse:sles:12"
    $ rpm -qf /usr/lib/systemd/system/ntpd.service
    ntp-4.2.6p5-44.1.x86_64

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
$::lsbmajdistrelease = 12 is identical for SLES 12 and Opensuse 12. But the service names need to be different for each distribution.
You can use $::operatingsystem or $::lsbdistdescription to distinguish between OpenSuse and SLES/SLED.

**Comment by Phil-Friderici** [comment]
:+1:

**Comment by ofsole** [comment]
works for me on SLES 12 & SLED 12.

**Comment by ghoneycutt** [comment]
Released in v3.6.1

Thank you everyone for getting involved!

**Pull request merged**
