### PR TITLE
Junk commit that adds a newline to the README to test travis

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
hahaha, did exactly the same yesterday ;)

**Comment by Phil-Friderici** [comment]
baam! broken :(

**Comment by ghoneycutt** [comment]
Ugh. Can't reproduce this failure locally.

**Comment by Phil-Friderici** [comment]
same here

**Comment by Phil-Friderici** [comment]
this is what I was meaning with "good luck"

**Comment by Phil-Friderici** [comment]
by accident I can reproduce the error locally.
I setup a new system for development with Gepetto today and now I have the same errors locally.
But to be honest I have no clue why or what's going on.

Maybe it's related to the version of the installed gems. This is the list of the affected system:
<pre>
*** LOCAL GEMS ***

bundler (1.8.0)
diff-lcs (1.2.5)
facter (1.7.6)
hiera (1.3.4)
json_pure (1.8.2)
librarian-puppet-simple (0.0.3)
metaclass (0.0.4)
mocha (1.1.0)
puppet (3.7.4)
puppet-lint (1.1.0)
puppet-syntax (1.4.1)
puppetlabs_spec_helper (0.8.2)
rake (10.4.2)
rspec (2.99.0)
rspec-core (3.2.0, 2.99.2)
rspec-expectations (3.2.0, 2.99.2)
rspec-mocks (3.2.0, 2.99.3)
rspec-puppet (2.0.0)
rspec-support (3.2.1)
thor (0.19.1)
</pre>

**Comment by ghoneycutt** [comment]
the rspec-* bits seemed inline with mine except for rspec-puppet, which is testing now. If that fails to produce results, I guess we can try pinning the versions of all the gems and working through that. 

Here's what works in my setup

<pre>
ntp$ bundle exec gem list

*** LOCAL GEMS ***

bundler (1.5.3)
CFPropertyList (2.2.8)
diff-lcs (1.2.5)
facter (2.2.0 universal-darwin)
hiera (1.3.4)
json_pure (1.8.1)
metaclass (0.0.4)
mocha (1.1.0)
puppet (3.7.1)
puppet-lint (1.0.1)
puppet-syntax (1.3.0)
puppetlabs_spec_helper (0.8.1)
rake (10.3.2)
rspec (3.1.0)
rspec-core (3.1.4)
rspec-expectations (3.1.1)
rspec-mocks (3.1.1)
rspec-puppet (1.0.1)
rspec-support (3.1.0)
</pre>

**Comment by ghoneycutt** [comment]
Here's the broken travis running ruby 1.9.3 and puppet 3.7.4

https://travis-ci.org/ghoneycutt/puppet-module-ntp/jobs/50639666

<pre>
IInstalling CFPropertyList 2.2.8
Installing rake 10.4.2
Installing diff-lcs 1.2.5
Installing json_pure 1.8.2
Installing facter 2.4.1
Installing metaclass 0.0.4
Installing puppet-lint 1.1.0
Installing rspec-core 2.99.2 Using bundler 1.7.6
Installing rspec-mocks 2.99.3
Installing puppet-syntax 1.4.1
Installing rspec-expectations 2.99.2
Installing hiera 1.3.4
Installing rspec 2.99.0
Installing mocha 1.1.0
Installing rspec-puppet 2.0.0
Installing puppetlabs_spec_helper 0.8.2
Installing puppet 3.7.4
</pre>

**Comment by Phil-Friderici** [comment]
it's related to rspec-puppet 2.0.0, with rspec-puppet 1.0.1 it works

**Comment by Phil-Friderici** [comment]
adding
<pre>
gem 'rspec-puppet', '1.0.1'
</pre>
to Gemfile helped a lot :)

**Comment by Phil-Friderici** [comment]
here's our problem: https://github.com/rodjek/rspec-puppet/issues/253

**Comment by ghoneycutt** [comment]
Hmm.. it is still failing though I updated the Gemfile to 1.0.1

**Comment by ghoneycutt** [comment]
Trying again with the fix that Dan is using in bodepd/puppet-rjil

**Comment by ghoneycutt** [comment]
Tried `1.0.1` and `~>1.0` and both yield the same failing results

https://travis-ci.org/ghoneycutt/puppet-module-ntp/builds/50658990

**Comment by Phil-Friderici** [comment]
add this:```gem 'rspec', '2.99.0'```
worked for me here https://github.com/Phil-Friderici/puppet-module-afs/pull/32

**Comment by ghoneycutt** [comment]
Hmm.. works except for ruby 1.8.7

**Comment by Phil-Friderici** [comment]
WTF?: All of them were green in my commit...
Maybe I need a break ;)

**Comment by Phil-Friderici** [comment]
all green here :)

**Comment by Phil-Friderici** [comment]
@ghoneycutt thanks for merging
Without changing, my afs build is also got green again.
Definitly time for "have a nice weekend !"

**Pull request merged**
